[package]
name = "gbcemu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gbcemu"
path = "src/main.rs"

[[bin]]
name = "test_runner"
path = "src/test_runner.rs"

[build-dependencies]
cc = "1"

[dependencies]
sdl3 = { version = "0.17", features = ["hidapi"] }
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
image = "0.25"
